version: "3"

services:
  datastore:
    build:
      context: ./datastore
      dockerfile: Dockerfile
    tty: true
    environment:
      DATASTORE_PROJECT_ID: app
      DATASTORE_LISTEN_ADDRESS: 0.0.0.0:8081
    ports:
      - "8081:8081"
  cloudgui:
    build:
      context: ./cloudgui
      dockerfile: Dockerfile
    ports:
      - "8082:8000"
    depends_on:
      - datastore
    logging:
      driver: none
